### ISSUE TITLE
Changelog is not generated correctly

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-ruby#25]
The order of the instructions in the readme was changed in #22

[github-changelog-generator](https://github.com/skywinder/github-changelog-generator) (which we use to generate the changelog) needs the git tags that `rake release` creates.

Right now you need to update the latest version in the changelog as it just says `Unreleased` instead of the actual version.

Found a flag you can give to the generator so it adds the correct version: https://github.com/skywinder/github-changelog-generator/blob/138abfe67666da4368615f3a5d98d538edd8dc44/lib/github_changelog_generator/parser.rb#L143

**Comment by roback** [comment]
Another issue with the changelog generator is that it [orders the tags by the date of the commit, not by the date it was tagged](https://github.com/skywinder/github-changelog-generator/blob/99ffa3692b07a510bd9c913d9c101f837b5bd174/lib/github_changelog_generator/fetcher.rb#L194-L204). Since the commit for `v3.0.0` was done before `v2.0.2` they gets added in the wrong order into the CHANGELOG.md file.

I have corrected the date of the tags so they are in the right order on the releases page (which orders by tag date), but the commit-dates are still in the wrong order.

(The reason this happened was that we wanted to release the gem under the new name (`twingly-search`) before we deprecated the old one (`twingly-analytics`).)

**Comment by twingly-mob** [comment]
We'll remove the 2.0.2 tag for now. We can report a feature request upstream and put it back if they "fix" it.

**Comment by roback** [comment]
I have removed the `v2.0.2` tag so the changelog gets generated correctly.

The changelog contains urls to compare two releases. In the case of `v2.0.2` it looks like this (the releases is in the wrong order):

```
https://github.com/twingly/twingly-search-api-ruby/compare/v3.0.0...v2.0.2
```

Im not sure that we can put `v2.0.2` back, and I don't think this can be "fixed" upstream.

**Comment by roback** [comment]
Im closing this as it can't be solved. Even if the changelog generator puts the tags in "tag-date" order, the list of PRs and issues that has been closed between the releases will be wrong.

We have to live without the `v2.0.2` tag and release :(

(I removed the `v2.0.2` tag with `git tag -d v2.0.2 && git push origin :refs/tags/v2.0.2`)

**Comment by roback** [comment]
> (I removed the v2.0.2 tag with git tag -d v2.0.2 && git push origin :refs/tags/v2.0.2)

Everyone has to remove the `2.0.2` tag locally if they haven't done so already to be able to release the gem (the release command pushes all local tags to the remote).

@twingly/dev 

Perhaps a little too late for @walro though :stuck_out_tongue:

**Comment by dentarg** [comment]
Thanks for the notice, I didn't have it :)
