### ISSUE TITLE
Take <post> contentType into account

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-ruby#36]
According to https://developer.twingly.com/resources/search/ the [`<post>` tag](https://github.com/twingly/twingly-search-api-ruby/blob/79f184d4752fca1255ed891c58bdb70a0696f30d/lib/twingly/search/parser.rb#L31) we parse have an attribute `contentType`:

```xml
<post contentType="blog">
```

* `post` - the root element for a blog post
  * `contentType` - currently, the only available type is blog

Shouldn't the client take that into consideration?

**Comment by jage** [comment]
> Shouldn't the client take that into consideration?

Good question. Currently we're only serving blogs through Twingly Search API. But for new API versions we might serve other content types. We'll probably want to only select posts with content type "blog" and discard other posts (which will be none currently).
