### ISSUE TITLE
endpoint_url is unused

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-ruby#39]
https://github.com/twingly/twingly-search-api-ruby/blob/72cec57ae11a1f865f9044d7bf1c7de38a2cb147/lib/twingly/search/client.rb#L52-L53

**Comment by jage** [comment]
Isn't it used in https://github.com/twingly/twingly-search-api-ruby/blob/72cec57ae11a1f865f9044d7bf1c7de38a2cb147/lib/twingly/search/query.rb#L27?

**Comment by walro** [comment]
Yeah, I noticed that when starting to remove things. I wonder what I did wrong when searching though....

However, the dependency is quite strange. It's not used by the class itself, but other classes rely on it.

**Comment by walro** [comment]
> Yeah, I noticed that when starting to remove things. I wonder what I did wrong when searching though....

Ah, I only searched `/spec`, forgot that I had that there... :)

**Comment by walro** [comment]
> However, the dependency is quite strange, isn't it? It's not used by the class itself, but other classes rely on it.

I'll let that slide :)
