### ISSUE TITLE
Query#start_time and #end_time should be converted to UTC

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-ruby#43]
Nowhere in the gem documentation do we mention that `Query#start_time` and `Query#end_time` expects that the time is in UTC. It is explained on [developer.twingly.com](https://developer.twingly.com/resources/search/#api-endpoint) but not here. It is explained for the `Post` class though.

The hello world example needs an update too (`Time.now` -> `Time.now.utc`).

**Comment by jage** [comment]
How about we also include a warning when it's passed non-UTC objects?

I'm thinking something like:

```Ruby
warn "Time needs to be in UTC" unless start_time.now.utc?
```

**Comment by roback** [comment]
Good idea.

Maby [RSpec's output matcher](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/output-matcher) could be used for testing.

**Comment by jage** [comment]
> Maby RSpec's output matcher could be used for testing.

:+1:

**Comment by dentarg** [comment]
:+1:

**Comment by roback** [comment]
We have decided not to go with the warning, but instead convert `start_time` and `end_time` to UTC so the user don't have to think about that themselves. Ill update the issue title.
