### ISSUE TITLE
Add fixture for "Invalid language code(s)"

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-ruby#56]
For the search pattern `shoes lang:asdf` I got this XML back:

``` xml
<blogstream xmlns="http://www.twingly.com">
<operationResult resultType="failure">
Search was unable to proceed: Invalid language code(s)
</operationResult>
</blogstream>
```

**Comment by roback** [comment]
A response from Search API v3 looks like:

```xml
<error code="40002">
<message>Invalid language code(s) for parameter: Lang</message>
</error>
```

All errors in v3 follows the same structure as above. We already have a fixture for a similar error: https://github.com/twingly/twingly-search-api-ruby/blob/785d8604c2422eee7a1abc26422649fcdc57f861/spec/fixtures/nonexistent_api_key_result.xml#L1-L3

I'll just close this issue.
