### ISSUE TITLE
rack-2.0.1 requires ruby version >= 2.2.2, which is incompatible with the current version

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-ruby#58]
Tests fail for all versions except 2.3.0: https://travis-ci.org/twingly/twingly-search-api-ruby/builds/159866314

E.g. 1.9.3: https://travis-ci.org/twingly/twingly-search-api-ruby/jobs/159866315

```
$ gem update bundler
Updating installed gems
Updating bundler
Fetching: bundler-1.13.1.gem (100%)
Successfully installed bundler-1.13.1
Gems updated: bundler
13.09s$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
rack-2.0.1 requires ruby version >= 2.2.2, which is incompatible with the
current version, ruby 1.9.3p551
```

I guess we need to limit either webmock or vcr (development dependencies).

**Comment by dentarg** [comment]
Oh, it is github_changelog_generator -> github_api -> oauth2 -> rack

**Comment by jage** [comment]
> Oh, it is github_changelog_generator -> github_api -> oauth2 -> rack

Couldn't we kick it out of the gemspec?

**Comment by dentarg** [comment]
I think we should remove github_changelog_generator from the gemspec... :)
