### ISSUE TITLE
Ruby 1.9.3 and Ruby 2.0.0 can't use nokogiri >= 1.7.0 (build failures)

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-ruby#61]
https://travis-ci.org/twingly/twingly-search-api-ruby/builds/187490356

> nokogiri-1.7.0 requires ruby version >= 2.1.0

Drop Ruby 1.9.3 and Ruby 2.0.0 support or limit us to Nokogiri < 1.7.0?

**Comment by dentarg** [comment]
Or add some code to the gemspec checking `RUBY_VERSION`?

**Comment by jage** [comment]
> Drop Ruby 1.9.3 and Ruby 2.0.0 support or limit us to Nokogiri < 1.7.0?

I think we can drop 1.9.3 and 2.0.0 since they are supported anymore, the old version of the gem will continue to work (without newer features) until the current API version is deprecated.

**Comment by dentarg** [comment]
> the old version of the gem will continue to work

Yeah, I guess bundler / nokogiri is smart enough not trying to install Nokogiri 1.7.0 when you are using 1.9.3 or 2.0.0. 

I don't think we need to release a new explicitly dropping support for 1.9.3 and 2.0.0. We can just remove their entires from `.travis.yml` and update the README. I think even new versions of the this gem can continue work on 1.9.3 or 2.0.0, but we wont make sure they work.

**Comment by dentarg** [comment]
> Yeah, I guess bundler / nokogiri is smart enough not trying to install Nokogiri 1.7.0 when you are using 1.9.3 or 2.0.0.

Ah, not true, see the failed Travis builds. But if you already have some other Nokogiri version, or install it before you try to install twingly-search, you can install the gem fine.

**Comment by dentarg** [comment]
Ah, the gemspec has "required_ruby_version"
