### ISSUE TITLE
Missing comma and space in inspect methods

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-ruby#66]
Example

```ruby
#<Twingly::Search::Result:0x3fc26a8a3448 @posts, @number_of_matches_returned=0, @number_of_matches_total=0@incomplete_result=false>
```

See

https://github.com/twingly/twingly-search-api-ruby/blob/v5.1.0/lib/twingly/livefeed/result.rb#L32
https://github.com/twingly/twingly-search-api-ruby/blob/v5.1.0/lib/twingly/search/result.rb#L40

**Comment by jage** [comment]
#79 is a duplicate of this, but with more info, will close this as a duplicate instead.
